# This only contains the parts that are different from the default config file.
# Title and introductory text.
report_comment: This protocol assigns Unique Molecular Identifiers from Read 1 to Read 2, and uses only Read 2 for analysis. All report sections present Read 2 as R1, Read 1 or read 1, except the FastQC and Download data section.

# Module and section comments
section_comments:
    fastqc: "Only QC results of read 2 are plotted here, because read 1 contains only UMI. Please contact us for reads 1 QC plots if interested."

# Order of modules
module_order:
    - fastqc:
        path_filters:
            - '*_R2_fastqc.zip'
    - Trim_Galore
    - trimming_2step
    - bbduk
    - star
    - rseqc
    - qualimap
    - picard
    - preseq
    - plot_ERCC
    - custom_content
    - featureCounts
    - plot_sample_distance
    - plot_gene_heatmap
    - DESeq2
    - gProfiler
    - DTU
