# Title and introductory text.
intro_text: This report includes summaries of data quality, data processing, and snapshots of results for your RNAseq study. Please consult <a href='https://zymo-research.github.io/pipeline-resources/report_docs/RNAseq_documentation.html' target='_blank'>our RNAseq report documentation</a> on how to use this report.
report_comment: If you have any question regarding this report, please contact us via the Aladdin platform.

extra_fn_clean_exts:
    - '.genome.primary'
    - '.rseqc'
    - '.ccurve'
    - '.bbduk'
    - type: truncate
      pattern: "_R1_val_1.fq.gz"
      module: bbduk

# Module and section comments
section_comments:
    fastqc: "Only QC results of read 1 are plotted here. Please contact us for reads 2 QC plots if interested."

# Order of modules
module_order:
    - fastqc:
        path_filters:
            - '*_R1_fastqc.zip'
    - Trim_Galore
    - trimming_2step
    - bbduk
    - star
    - rseqc
    - qualimap
    - picard
    - preseq
    - plot_ERCC
    - custom_content
    - featureCounts
    - plot_sample_distance
    - plot_gene_heatmap
    - DESeq2
    - gProfiler
    - DTU

# Order of sections
report_section_order:
    software_versions:
        order: -1000
    workflow_summary:
        order: -1100
    DupRadar:
        before: 'preseq'
    biotype-counts:
        after: 'salmon_quant'

table_columns_visible:
    FastQC:
        percent_duplicates: False
    Trim Galore:
        percent_trimmed: False
    cutadapt:
        percent_trimmed: False
    BBDuk:
        Total Removed bases percent: False
    'Custom content: DupRadar':
        dupRadar_intercept: False
    STAR:
        uniquely_mapped: False
    RSeQC:
        proper_pairs_percent: False
    QualiMap:
        reads_aligned: False
        5_3_bias: False

table_columns_placement:
    FastQC:
        total_sequences: 900
        percent_gc: 910
    Trim Galore:
        percent_pass_filter: 920
    cutadapt:
        percent_pass_filter: 920
    BBDuk:
        Total Removed reads percent: 925
    STAR:
        uniquely_mapped_percent: 930
    'Custom content: UMI-tools':
        kept_dedupped: 940
    Picard:
        PERCENT_DUPLICATION: 940
    'Custom content: Biotype Counts':
        rRNA: 950
        hemoglobin: 960
    'Custom content: Salmon quant':
        pct_assigned: 970
        reads_assigned: 980
    featureCounts:
        percent_assigned: 970
        Assigned: 980

remove_sections:
    - fastqc_sequence_counts
    - fastqc_sequence_duplication_levels
    - fastqc_status_checks
    - qualimap-reads-genomic-origin
    
#export_plots: true

log_filesize_limit: 50000000

disable_version_detection: true
skip_versions_section: true
